# contrib-wide Makefile include file, generated automatically with
# ./configure CXXFLAGS=-O2 -Wall -fPIC -pthread -m64 -I/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/root/5.34.19-x86_64-slc5-gcc4.3/include -fno-builtin-memcmp -DJETEDM_STANDALONE  LDFLAGS=-O2 -m64 FC=gfortran FCFLAGS=-O2 -fPIC --fastjet-config=/sx/caj24/testarea/ProofAna_git/utils/fastjet/fastjet-config --prefix=/sx/caj24/testarea/ProofAna_git/utils/fastjet/install-dir
CXXFLAGS=-O2 -Wall -fPIC -pthread -m64 -I/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/root/5.34.19-x86_64-slc5-gcc4.3/include -fno-builtin-memcmp -DJETEDM_STANDALONE 
LDFLAGS=-O2 -m64
FC=gfortran
FCFLAGS=-O2 -fPIC
FASTJETCONFIG=/sx/caj24/testarea/ProofAna_git/utils/fastjet/fastjet-config
PREFIX=/sx/caj24/testarea/ProofAna_git/utils/fastjet/install-dir
install_script = $(SHELL) ../utils/install-sh
check_script = ../utils/check.sh
