# contrib-wide Makefile include file, generated automatically with
# ./configure CXXFLAGS=-O2 -pipe -Wall -W -Woverloaded-virtual -pthread -stdlib=libc++ -std=c++11 -m64 -I/Users/Alex/Desktop/HEP/ROOT6/include -Qunused-arguments -DJETEDM_STANDALONE  LDFLAGS=-O2 -mmacosx-version-min=10.10 -m64 FC=gfortran FCFLAGS=-O2 -fPIC --fastjet-config=/Users/Alex/Desktop/ProofAna/utils/fastjet/fastjet-config --prefix=/Users/Alex/Desktop/ProofAna/utils/fastjet/install-dir
CXXFLAGS=-O2 -pipe -Wall -W -Woverloaded-virtual -pthread -stdlib=libc++ -std=c++11 -m64 -I/Users/Alex/Desktop/HEP/ROOT6/include -Qunused-arguments -DJETEDM_STANDALONE 
LDFLAGS=-O2 -mmacosx-version-min=10.10 -m64
FC=gfortran
FCFLAGS=-O2 -fPIC
FASTJETCONFIG=/Users/Alex/Desktop/ProofAna/utils/fastjet/fastjet-config
PREFIX=/Users/Alex/Desktop/ProofAna/utils/fastjet/install-dir
install_script = $(SHELL) ../utils/install-sh
check_script = ../utils/check.sh
